apiVersion: v1
kind: Pod
metadata:
  name: image-volume-fallback
spec:
  volumes:
  - name: data
    emptyDir: {}
  initContainers:
  - name: init
    image: busybox
    command: ["sh","-c","set -e; mkdir -p /data; echo 'Hello from image!' > /data/hello.txt"]
    volumeMounts:
    - name: data
      mountPath: /data
  containers:
  - name: app
    image: busybox
    command: ["sh","-c","cat /data/hello.txt; sleep 3600"]
    volumeMounts:
    - name: data
      mountPath: /data
