apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-index
  namespace: sidecar-132
data:
  index.html: |
    <!doctype html>
    <html>
      <head><meta charset="utf-8"><title>Demo Sidecar Logs</title></head>
      <body>
        <h1>Hello from Nginx + Sidecar (K8s 1.32)</h1>
        <p>Refresh a few times to generate access logs.</p>
      </body>
    </html>
