apiVersion: v1
kind: Pod
metadata:
  name: resize-pod
  namespace: resize-demo
  labels:
    app: resize
spec:
  containers:
  - name: app
    image: busybox:stable
    command: ["sh","-c","sleep infinity"]
    resources:
      requests:
        cpu: "50m"
        memory: "32Mi"
      limits:
        cpu: "100m"
        memory: "64Mi"
