apiVersion: v1
kind: Pod
metadata:
  name: pod0
  namespace: default
spec:
  resourceClaims:
  - name: gpu
    resourceClaimName: some-gpu
  containers:
  - name: app
    image: busybox:stable
    command: ["sh","-c","echo hello DRA && sleep 3600"]
