apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-index
  namespace: sidecar-133
data:
  index.html: |
    <!doctype html>
    <html>
      <head><meta charset="utf-8"><title>Demo Sidecar Logs (1.33)</title></head>
      <body>
        <h1>Hello from Nginx + Native Sidecar (K8s 1.33)</h1>
        <p>Refresh a few times to generate access logs.</p>
      </body>
    </html>
