apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-nginx-conf
  namespace: sidecar-133
data:
  nginx.conf: |
    events {}
    http {
      include       mime.types;
      default_type  application/octet-stream;

      # Log su volume condiviso
      access_log /var/log/nginx/access.log;
      error_log  /var/log/nginx/error.log warn;

      sendfile        on;
      keepalive_timeout  65;

      server {
        listen 80;
        server_name _;

        root /usr/share/nginx/html;
        index index.html;

        location / {
          try_files $uri $uri/ =404;
        }
      }
    }

