apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-sidecar-133
  namespace: sidecar-133
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websidecar133
  template:
    metadata:
      labels:
        app: websidecar133
    spec:
      volumes:
        - name: html
          configMap:
            name: demo-index
        - name: nginx-conf
          configMap:
            name: demo-nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: logs
          emptyDir: {}
      #Sidecar nativo: initContainer con restartPolicy: Always (1.33)
      initContainers:
        - name: log-reader
          image: busybox:stable
          restartPolicy: Always
          command: ["sh","-c","tail -F /var/log/nginx/access.log"]
          volumeMounts:
            - name: logs
              mountPath: /var/log/nginx
      containers:
        - name: nginx
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: logs
              mountPath: /var/log/nginx
---
apiVersion: v1
kind: Service
metadata:
  name: web-sidecar-133-svc
  namespace: sidecar-133
spec:
  type: NodePort
  selector:
    app: websidecar133
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081
